model:
  world_model:
    emb_dim: 1024
    z_dim: 32
    num_classes: 32
    h_dim: 600
    hidden_dim: 600
    num_layers_za2hidden: 1
    num_layers_h2z: 1
    mlp_hidden_dim: 400
    min_std: 0.1
    kl_balance_alpha: 0.8
    kl_loss_scale: 0.1
  explorer:
    num_emsembles: 10
    emsembles_offset: 1
    emsembles_target_mode: 'z'
    mlp_hidden_dim: 400
    min_std: 0.1
    discount: 0.99
    lambda_: 0.95
    actor_entropy_scale: 0.0001
    slow_critic_update: 100
  achiever:
    num_positives: 256
    neg_sampling_factor: 0.1
    mlp_hidden_dim: 400
    min_std: 0.1
    discount: 0.99
    lambda_: 0.95
    actor_entropy_scale: 0.0001
    slow_critic_update: 100

env:
  task: 'FrankaKitchen'
  img_size: 128
  action_repeat: 2
  time_limit: 1000

data:
  buffer_size: 2000
  batch_size: 50
  seq_length: 50
  imagination_horizon: 15

learning:
  seed_steps: 1000
  num_steps: 10000000
  expl_episode_freq: 2
  world_model_lr: 0.0002
  explorer_actor_lr: 0.00004
  explorer_critic_lr: 0.0001
  achiever_actor_lr: 0.00004
  achiever_critic_lr: 0.0001
  epsilon: 0.00001
  weight_decay: 0.000001
  grad_clip: 100
  update_freq: 4
  eval_episode_freq: 5

wandb:
  logging: false
  name: 'lexa'
  group: ''
  project: 'LEXA'

device: 'cuda'
seed: 0
